// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LogininwalidemailTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void logininwalidemail() {
    driver.Navigate().GoToUrl("https://www.obuvki.bg/");
    driver.Manage().Window.Size = new System.Drawing.Size(1302, 698);
    driver.FindElement(By.LinkText("Вход")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".e-header-cart-button__icon path"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.Id("login[username]")).Click();
    driver.FindElement(By.Id("login[username]")).SendKeys("alabala@mn.kl");
    driver.FindElement(By.CssSelector(".input-wrapper--type-password > .input-wrapper__label")).Click();
    driver.FindElement(By.Id("login[password]")).SendKeys("alabala");
    driver.FindElement(By.Name("send")).Click();
    driver.FindElement(By.CssSelector(".global-notices__item > span")).Click();
    driver.FindElement(By.CssSelector(".global-notices__item > span")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".global-notices__item > span"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".global-notices__item > span")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".global-notices__item > span")).Text, Is.EqualTo("Грешно потребителско име или парола."));
    driver.Close();
  }
}
