// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestSearchTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testSearch() {
    driver.Navigate().GoToUrl("https://softuni.bg/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.CssSelector(".cell > .fa")).Click();
    driver.FindElement(By.CssSelector(".container > form #search-input")).Click();
    driver.FindElement(By.CssSelector(".container > form #search-input")).SendKeys("qa");
    driver.FindElement(By.CssSelector(".container > form #search-input")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".main-container")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".search-title")).Text, Is.EqualTo("Резултати от търсене на “qa”"));
    driver.Close();
  }
}
