// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestInvalidUsernameAndPasswordTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testInvalidUsernameAndPassword() {
    driver.Navigate().GoToUrl("https://softuni.bg/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.CssSelector(".softuni-btn-primary")).Click();
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.CssSelector(".authentication-page-form")).Click();
    driver.FindElement(By.Id("username")).SendKeys("user1");
    driver.FindElement(By.CssSelector(".authentication-page-form")).Click();
    driver.FindElement(By.Id("password-input")).SendKeys("user1");
    driver.FindElement(By.CssSelector(".softuni-btn")).Click();
    driver.FindElement(By.CssSelector("li")).Click();
    Assert.That(driver.FindElement(By.CssSelector("li")).Text, Is.EqualTo("Невалидно потребителско име или парола"));
    driver.Close();
  }
}
