// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class OpenWikipediaAndSearchForQATest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void openWikipediaAndSearchForQA() {
    driver.Navigate().GoToUrl("https://www.wikipedia.org/");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 774);
    driver.FindElement(By.Id("searchInput")).Click();
    driver.FindElement(By.Id("searchInput")).SendKeys("Quality assurance");
    driver.FindElement(By.CssSelector(".svg-search-icon")).Click();
    driver.FindElement(By.Id("firstHeading")).Click();
    Assert.That(driver.FindElement(By.Id("firstHeading")).Text, Is.EqualTo("Quality assurance"));
    driver.FindElement(By.CssSelector("ul:nth-child(56) > li:nth-child(1)")).Click();
    driver.FindElement(By.LinkText("Best practice")).Click();
    driver.FindElement(By.Id("firstHeading")).Click();
    Assert.That(driver.FindElement(By.Id("firstHeading")).Text, Is.EqualTo("Best practice"));
    driver.Close();
  }
}
